INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Animal', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Activity', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Body Parts', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Colors', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Cutlery', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Flags', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Food', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Fruit', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Objects', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Shapes', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Sports', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Vegetable', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('People', DEFAULT);
INSERT INTO tapnlearn.category (name, is_deleted) VALUES ('Flower', DEFAULT);

INSERT INTO tapnlearn.sub_category (category_id, name, is_deleted) VALUES (1, 'Domestic Animals', DEFAULT);
INSERT INTO tapnlearn.sub_category (category_id, name, is_deleted) VALUES (1, 'Wild Animals', DEFAULT);
INSERT INTO tapnlearn.sub_category (category_id, name, is_deleted) VALUES (1, 'Sea Animals', DEFAULT);
INSERT INTO tapnlearn.sub_category (category_id, name, is_deleted) VALUES (1, 'Baby Animals', DEFAULT);

INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Bear', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Buffalo', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Cat', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Dog', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Chicken', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Cow', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Elephant', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Fox', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Giraffe', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Horse', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Lion', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Ox', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Panda', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Rabbit', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Rhinoceros', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Snake', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Tiger', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (1, null, 'Wolf', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (2, null, 'Cycling', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (2, null, 'Dancing', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (2, null, 'Hiking', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (2, null, 'Running', DEFAULT);
INSERT INTO tapnlearn.resource (category_id, sub_category_id, name, is_deleted) VALUES (2, null, 'Swimming', DEFAULT);

INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (1, 'animals/bear.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (2, 'animals/Buffalo.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (3, 'animals/Cat.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (4, 'animals/Dog.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (5, 'animals/Chicken.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (6, 'animals/cow.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (7, 'animals/Elephant.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (8, 'animals/Fox.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (9, 'animals/Giraffe.webp', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (10, 'animals/Horse.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (11, 'animals/Lion.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (12, 'animals/ox.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (13, 'animals/panda.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (14, 'animals/rabbit.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (15, 'animals/rihno.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (16, 'animals/snake.png', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (17, 'animals/Tiger.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (18, 'animals/Wolf.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (19, 'activity/Cycling.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (20, 'activity/Dancing.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (21, 'activity/Hiking.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (22, 'activity/Running.jpg', DEFAULT);
INSERT INTO tapnlearn.resource_picture (resource_id, picture_path, is_deleted) VALUES (23, 'activity/Swimming.jpg', DEFAULT);
